### ISSUE TITLE
Groovy Script to import phenotypes back into qupath

### ISSUE THREAD

**Issue by quarkstar-codes** [adyprat/akoya_webinar_0622#1]
Hi Aditya,

You showed a Qupath groovy script during the webinar that imported the phenotypes from the output_phenotype.csv back into Qupath.

Would you be able to also provide the script in this github repo?

Thank you!

**Comment by LiorLuo** [comment]
same question as Aditya asked, thanks for your sharing.

**Comment by adyprat** [comment]
Apologies for the confusion. It is linked here: https://github.com/adyprat/akoya_webinar_0622/tree/main/notebooks

 or here: https://gist.github.com/adyprat/25a0c22a7d02b71279ee9e7545ef4f94
